// <auto-generated />
using BoardGame.Service.Data;
using BoardGame.Service.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace BoardGame.Service.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181101233415_AddingSpecialMovesToDb")]
    partial class AddingSpecialMovesToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoardGame.Service.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("Bot");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("BoardGame.Service.Models.Data.DbChessGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlackPlayerId");

                    b.Property<DateTime>("ChallengeDate");

                    b.Property<string>("InitiatedById");

                    b.Property<DateTime>("LastMoveDate");

                    b.Property<string>("Name");

                    b.Property<string>("OpponentId");

                    b.Property<int>("Status");

                    b.Property<string>("WhitePlayerId");

                    b.HasKey("Id");

                    b.HasIndex("BlackPlayerId");

                    b.HasIndex("InitiatedById");

                    b.HasIndex("OpponentId");

                    b.HasIndex("WhitePlayerId");

                    b.ToTable("ChessGames");
                });

            modelBuilder.Entity("BoardGame.Service.Models.Data.Moves.DbBaseMove", b =>
                {
                    b.Property<Guid>("MoveId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChessMoveType")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("DbChessGameId");

                    b.Property<int>("Owner");

                    b.HasKey("MoveId");

                    b.HasIndex("DbChessGameId");

                    b.ToTable("ChessMoves");

                    b.HasDiscriminator<string>("ChessMoveType").HasValue("DbBaseMove");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BoardGame.Service.Models.Data.Moves.DbChessMove", b =>
                {
                    b.HasBaseType("BoardGame.Service.Models.Data.Moves.DbBaseMove");

                    b.Property<string>("FromColumn");

                    b.Property<int>("FromRow");

                    b.Property<string>("ToColumn");

                    b.Property<int>("ToRow");

                    b.ToTable("ChessMoves");

                    b.HasDiscriminator().HasValue("DbChessMove");
                });

            modelBuilder.Entity("BoardGame.Service.Models.Data.Moves.DbKingCastlingMove", b =>
                {
                    b.HasBaseType("BoardGame.Service.Models.Data.Moves.DbChessMove");

                    b.Property<int>("CastlingType");

                    b.ToTable("ChessMoves");

                    b.HasDiscriminator().HasValue("DbKingCastlingMove");
                });

            modelBuilder.Entity("BoardGame.Service.Models.Data.Moves.DbPawnEnPassantMove", b =>
                {
                    b.HasBaseType("BoardGame.Service.Models.Data.Moves.DbChessMove");

                    b.Property<string>("CapturePositionColumn");

                    b.Property<int>("CapturePositionRow");

                    b.ToTable("ChessMoves");

                    b.HasDiscriminator().HasValue("DbPawnEnPassantMove");
                });

            modelBuilder.Entity("BoardGame.Service.Models.Data.Moves.DbPawnPromotionalMove", b =>
                {
                    b.HasBaseType("BoardGame.Service.Models.Data.Moves.DbChessMove");

                    b.Property<int>("PromoteTo");

                    b.ToTable("ChessMoves");

                    b.HasDiscriminator().HasValue("DbPawnPromotionalMove");
                });

            modelBuilder.Entity("BoardGame.Service.Models.Data.DbChessGame", b =>
                {
                    b.HasOne("BoardGame.Service.Models.ApplicationUser", "BlackPlayer")
                        .WithMany()
                        .HasForeignKey("BlackPlayerId");

                    b.HasOne("BoardGame.Service.Models.ApplicationUser", "InitiatedBy")
                        .WithMany()
                        .HasForeignKey("InitiatedById");

                    b.HasOne("BoardGame.Service.Models.ApplicationUser", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentId");

                    b.HasOne("BoardGame.Service.Models.ApplicationUser", "WhitePlayer")
                        .WithMany()
                        .HasForeignKey("WhitePlayerId");
                });

            modelBuilder.Entity("BoardGame.Service.Models.Data.Moves.DbBaseMove", b =>
                {
                    b.HasOne("BoardGame.Service.Models.Data.DbChessGame")
                        .WithMany("History")
                        .HasForeignKey("DbChessGameId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BoardGame.Service.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BoardGame.Service.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BoardGame.Service.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BoardGame.Service.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
